#!/bin/sh
~/Documents/iac/lab0-devtools/tools/attach_usb.sh
ls /dev/ttyU*
# cleanup
rm -rf obj_dir
rm -f pc_block.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace pc_block.sv --exe pc_block_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpc_block.mk Vpc_block

# run executable simulation file
obj_dir/Vpc_block
