module new_datamem #(
    parameter ADDRESS_WIDTH = 32,
              MEM_BYTES     = 16384,         
              BASE_ADDR     = 32'h0002_0000,
              DATA_WIDTH    = 32
)(
    input  logic                     MemWrite,
    input  logic [DATA_WIDTH-1:0]    WD,
    input  logic [1:0]               SizeWrite,    // 00=byte, 01=half, 10=word
    input  logic [ADDRESS_WIDTH-1:0] A,            // byte address
    input  logic [1:0]               LoadSize,     // same encoding for loads
    input  logic                     LoadUnsigned,
    input  logic                     clk,
    output logic [DATA_WIDTH-1:0]    dout
);

    localparam WORDS     = MEM_BYTES / 4;
    localparam ADDR_BITS = $clog2(WORDS);

    logic [ADDRESS_WIDTH-1:0] local_addr;
    logic [ADDR_BITS-1:0]     word_index;
    logic [1:0]               byte_offset;

    logic [DATA_WIDTH-1:0]    raw_word;
    logic [3:0]               byteena;
	 logic [31:0]              data;

    assign local_addr  = A - BASE_ADDR;
    assign word_index  = local_addr[ADDR_BITS+1 : 2];  // word index
    assign byte_offset = local_addr[1:0];              // which byte inside word

    // generate byte enables for stores (SB/SH/SW)
    always_comb begin
        byteena = 4'b0000;
        unique case (SizeWrite)
            2'b00: begin
                // store byte
                byteena = 4'b0001 << byte_offset;
            end
            2'b01: begin
                // store halfword (assume naturally aligned)
                if (byte_offset[1] == 1'b0)
                    byteena = 4'b0011;
                else
                    byteena = 4'b1100;
            end
            default: begin
                // store word
                byteena = 4'b1111;
            end
        endcase
    end

    // IP block generated by Quartus 
    dmem_ram dmem_inst (
        .clock   (clk),
        .address (word_index),
        .data    (WD),
        .wren    (MemWrite),
        .byteena (byteena),
        .q       (raw_word)
    );

    // load-side logic: LB/LH/LW, signed/unsigned
    always_comb begin
        data = raw_word;
        unique case (LoadSize)
            2'b00: begin
                // byte load
                logic [7:0] b;
                b = data >> (8 * byte_offset);
                if (LoadUnsigned)
                    dout = {24'b0, b};
                else
                    dout = {{24{b[7]}}, b};
            end
            2'b01: begin
                // halfword load (use bit 1 of offset)
                logic [15:0] h;
                h = data >> (16 * byte_offset[1]);
                if (LoadUnsigned)
                    dout = {16'b0, h};
                else
                    dout = {{16{h[15]}}, h};
            end
            default: begin
                // word load
                dout = data;
            end
        endcase
    end

endmodule