module new_insmem #(
    parameter ADDRESS_WIDTH = 32,
              MEM_BYTES     = 8192,          
              BASE_ADDR     = 32'hBFC00000
)(
    input  logic                     clk,
    input  logic [ADDRESS_WIDTH-1:0] addr,     // byte address (PC)
    output logic [31:0]              instr
);

    localparam WORDS     = MEM_BYTES / 4;
    localparam ADDR_BITS = $clog2(WORDS);

    logic [ADDRESS_WIDTH-1:0] local_addr;
    logic [ADDR_BITS-1:0]     word_index;
    logic [31:0]              q;

    assign local_addr = addr - BASE_ADDR;
    assign word_index = local_addr[ADDR_BITS+1 : 2];  // drop bottom 2 bits

    // IP block generated by Quartus 
    imem_ram imem_inst (
        .clock   (clk),
        .address (word_index),
        .data    (32'b0),   // never write: treat as ROM
        .wren    (1'b0),
        .q       (q)
    );

    assign instr = q;

endmodule